name: Job Dependencies

on:
  workflow_dispatch: # Allows you to run it manually

jobs:
  independent_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🕵️ I am checking for security issues in parallel with the build..."
      - run: sleep 8

  build_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔨 Step 1 - Building the application..."
      - run: sleep 3

  test_job:
    needs: build_job # Waits ONLY for build_job
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Step 2 - Running the tests..."
      - run: sleep 3

  deploy_job:
    needs: [test_job, independent_check] # This job waits for BOTH jobs to finish!
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Step 3 - Deploying to production because tests AND security checks passed!"
